{% set name = "djangorestframework-guardian2" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9cb8c9cc8bd51ed2429282a21517cafbb8b815be0d0b62a163530fd113534a52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2
    - djangorestframework >=3.12
    - django-guardian >=2.4.0

test:
  imports:
    - rest_framework_guardian
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/johnthagen/django-rest-framework-guardian2
  summary: django-guardian support for Django REST Framework
  dev_url: https://github.com/johnthagen/django-rest-framework-guardian2
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexpilot11
